### PR TITLE
YouTube handles, StyleGuide redirect, Docs update.

### PR DESCRIPTION
**Pull request by WBilgini**
I changed the things that Moldy pointed out, hope it works now!

### CODE REVIEW

**Comment by WBilgini** [comment]
why. this is the 3rd time i had to fix it and i have to fix it AGAIN.

**Comment by MoldyMacaroniX** [comment]
Looks good. I’ll review it on a bit and merge it if all continues to look good

**Comment by WBilgini** [comment]
IT WOOORKS

**Comment by WBilgini** [comment]
Might even have the time for a developer docs relocation.

**Comment by WBilgini** [comment]
Ready to push.

**Comment by WBilgini** [comment]
> Looks good. I’ll review it in a bit and merge it if all continues to look good

Cool

**Review by MoldyMacaroniX — APPROVED** [review]
Looks good. I made some minor improvements.

**Pull request merged**
